# Generated by Django 4.1.7 on 2023-03-16 19:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('lifeStatus', models.CharField(choices=[('ALIVE', 'ALIVE'), ('DEAD', 'DEAD')], default='ALIVE', max_length=10)),
                ('chipping_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deathDateTime', models.CharField(blank=True, choices=[('2023-03-16T19:15:49.671032+00:00', '2023-03-16T19:15:49.671032+00:00')], default=None, max_length=50, null=True)),
                ('chipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(unique=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(unique=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='AnimalVisitedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_visit_location_point', models.DateTimeField()),
                ('location_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_location_point', to='it_app.locationpoint')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('animals', models.ManyToManyField(blank=True, related_name='animalTypes', to='it_app.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='chipping_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animals', to='it_app.locationpoint'),
        ),
        migrations.AddField(
            model_name='animal',
            name='visited_locations',
            field=models.ManyToManyField(related_name='visited_animals', to='it_app.animalvisitedlocation'),
        ),
    ]
